### ISSUE TITLE
improperly formatted dates on Today's schedule

### ISSUE THREAD

**Issue by toozej** [DanAlbert/whdsched#25]
written out dates (EX: Thursday, January 5, 2012) do not fit on their line properly. Most likely too many characters for the line/box.  

Happens on Chromium and Firefox, irregardless of screen resolution and window size. Arrow buttons still work properly however.

**Comment by DanAlbert** [comment]
If only fonts were standardized across platforms... Anyway, should be fixed now. Can you verify this?

**Comment by toozej** [comment]
Will do when I get home

On Jan 6, 2012, at 15:05, Dan Albert
reply@reply.github.com
wrote:

**Comment by toozej** [comment]
still not working properly. seems to do it with all months (shorter ones like May aren't left out), longer days of the week (Wednesday being the most common) and whatever days (single or double digit)

**Comment by toozej** [comment]
working as of 1/8/12 at 1600
